package sa_robocode.Helpers;

public enum MotionType {
    AVOIDING_BULLET,
    READY_TO_MOVE,
    MAKING_TURN,
    GOING_TO_DESTINATION,
    SPONTANEOUS_REVERSE,
    SPONTANEOUS_TURN,
    SPONTANEOUS_SPEED_LIMIT,
    DANGER_ZONE,
    STOPPED_ROTATION
}
